#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          commandbox-default
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Starts CommandBox server instance default
### END INIT INFO

PATH="/usr/bin"

case "$1" in
	start) sudo box server start name=default openbrowser=false saveSettings=false --force;;
	stop)  sudo box stop default;;
	restart|force-reload) sudo box restart default;;
	status) sudo box server status default;;
	*) echo "Usage: $0 {start|stop|restart|force-reload}" >&2; exit 1 ;;
esac

exit 0